[package]
name = "voxel_carving"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.25"
nalgebra="0.33"
ordered-float="4.2"
itertools="0.13"